# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AniimationsUnit4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AniimationsUnit4
  pod 'lottie-ios'

  target 'AniimationsUnit4Tests' do
    inherit! :search_paths
  end

  target 'AniimationsUnit4UITests' do
    # Pods for testing
  end

end
